#!/usr/bin/env python3
"""Structural validation of vectors.json against SPEC.md.

Runs before the reference implementation, so a malformed file is reported here rather
than surfacing inside every consumer's adapter where it looks like their bug.

Checks only shape, never cryptography - proving the artifacts verify is the reference
job's business.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUPPORTED_FORMAT = 3
SUPPORTED_JCS_FORMAT = 1

COMMON = {"name", "kind", "anchor_did"}
REQUIRED = {
    "credential": COMMON | {"credential_json", "expect"},
    "token": COMMON | {"credential_json", "token_cbor_hex", "action", "expect"},
    "presentation": COMMON
    | {"presentation_cbor_hex", "challenge_cbor_hex", "action", "max_age_secs", "expect"},
    # Format 3 added `expect` here, which is what the version bump records: the spec
    # increments the format whenever a case gains a required field. Requiring it (rather
    # than merely tolerating it) is the point of the gate - a runner that silently
    # skipped the accept/reject check would report success for a check it never ran.
    "token_chain": COMMON
    | {"token_cbor_hex", "expect", "expect_depth", "expect_chain_agent_dids"},
    "revocation": COMMON | {"list_json", "revoked_index", "clear_index"},
    # `anchor_did` carries the pinned ROOT for this kind, not the issuing key: under
    # rotation the relying party does not know the issuer DID in advance.
    "key_history": COMMON | {"key_history_json", "credential_json", "expect"},
    # `anchor_did` is the ORG anchor: the directory is verified under it.
    "approval_key": COMMON | {"directory_json", "evidence_json", "action", "expect"},
    # `anchor_did` is the FRAMEWORK anchor, not the credential's issuer.
    "trust_config": COMMON | {"config_json", "credential_json", "expect"},
}
HEX_FIELDS = ("token_cbor_hex", "presentation_cbor_hex", "challenge_cbor_hex")


def check_runner_agrees(errors: "list[str]") -> None:
    """The runner must accept the formats actually shipped here.

    The vector files are generated by the reference implementation; the runner is
    maintained by hand. Nothing forces them to move together, and once they did not: the
    generator advanced to format 3 while `run_vectors.py` still declared 2, so the runner
    rejected every case on sight. CI stayed green throughout, because the only job that
    would have run the runner does not execute until the reference package is published.

    So this gate reads the runner's declared constants and compares them to the files.
    Parsing a constant out of a sibling script is not elegant; shipping a runner that
    refuses its own vectors is worse, and that is the failure this exists to catch.
    """
    src = (ROOT / "runner" / "run_vectors.py").read_text(encoding="utf-8")
    for const, expected, fname in (
        ("SUPPORTED_FORMAT", SUPPORTED_FORMAT, "vectors.json"),
        ("SUPPORTED_JCS_FORMAT", SUPPORTED_JCS_FORMAT, "jcs_vectors.json"),
    ):
        m = re.search(rf"^{const}\s*=\s*(\d+)\s*$", src, re.MULTILINE)
        if m is None:
            errors.append(f"runner/run_vectors.py: could not find {const}")
        elif int(m.group(1)) != expected:
            errors.append(
                f"runner/run_vectors.py declares {const} = {m.group(1)}, but "
                f"{fname} is format {expected} - the runner would refuse every case"
            )


def check_jcs(errors: "list[str]") -> "int | None":
    """Validate the canonicalization suite. Returns the case count, or None on a fatal
    structural problem."""
    path = ROOT / "jcs_vectors.json"
    if not path.exists():
        errors.append("jcs_vectors.json is missing")
        return None
    suite = json.loads(path.read_text(encoding="utf-8"))

    if suite.get("format") != SUPPORTED_JCS_FORMAT:
        errors.append(
            f"jcs_vectors.json: format is {suite.get('format')!r}, "
            f"expected {SUPPORTED_JCS_FORMAT}"
        )
    for field in ("profile", "spec"):
        if not suite.get(field):
            errors.append(f"jcs_vectors.json: missing {field!r}")

    cases = suite.get("cases")
    if not isinstance(cases, list) or not cases:
        errors.append("jcs_vectors.json: 'cases' must be a non-empty array")
        return None

    for i, c in enumerate(cases):
        missing = {"value", "expected_jcs"} - set(c)
        if missing:
            errors.append(f"jcs_vectors.json[{i}]: missing {sorted(missing)}")
            continue
        if not isinstance(c["expected_jcs"], str):
            errors.append(f"jcs_vectors.json[{i}]: expected_jcs must be a string")
            continue
        # The expected output must itself be JSON, and must parse back to the input.
        # A vector whose expectation is not a faithful encoding of its own value is
        # worse than no vector: every implementation fails it and the file looks right.
        try:
            if json.loads(c["expected_jcs"]) != c["value"]:
                errors.append(
                    f"jcs_vectors.json[{i}]: expected_jcs does not round-trip to value"
                )
        except json.JSONDecodeError:
            errors.append(f"jcs_vectors.json[{i}]: expected_jcs is not valid JSON")
    return len(cases)


def main() -> int:
    errors: "list[str]" = []
    suite = json.loads((ROOT / "vectors.json").read_text(encoding="utf-8"))

    if suite.get("format") != SUPPORTED_FORMAT:
        errors.append(f"format is {suite.get('format')!r}, expected {SUPPORTED_FORMAT}")

    cases = suite.get("cases")
    if not isinstance(cases, list) or not cases:
        print("FAIL: 'cases' must be a non-empty array", file=sys.stderr)
        return 1

    seen: "set[str]" = set()
    for i, c in enumerate(cases):
        name = c.get("name", f"<case {i}>")
        if name in seen:
            errors.append(f"{name}: duplicate case name")
        seen.add(name)

        kind = c.get("kind")
        if kind not in REQUIRED:
            errors.append(f"{name}: unknown kind {kind!r} (SPEC.md defines {sorted(REQUIRED)})")
            continue

        missing = REQUIRED[kind] - set(c)
        if missing:
            errors.append(f"{name}: missing {sorted(missing)}")

        if "expect" in c and c["expect"] not in ("accept", "reject"):
            errors.append(f"{name}: expect must be 'accept' or 'reject', got {c['expect']!r}")

        if not str(c.get("anchor_did", "")).startswith("did:"):
            errors.append(f"{name}: anchor_did is not a DID")

        for f in HEX_FIELDS:
            if f in c:
                try:
                    if not bytes.fromhex(c[f]):
                        errors.append(f"{name}: {f} is empty")
                except ValueError:
                    errors.append(f"{name}: {f} is not valid hex")

        if kind == "token_chain":
            dids = c.get("expect_chain_agent_dids", [])
            if not isinstance(dids, list) or not dids:
                errors.append(f"{name}: expect_chain_agent_dids must be a non-empty array")
            elif len(set(dids)) != len(dids):
                errors.append(f"{name}: chain hops are not distinct")
            # depth is hop count minus the root, so the two must agree or one is wrong.
            elif c.get("expect_depth") != len(dids) - 1:
                errors.append(
                    f"{name}: expect_depth {c.get('expect_depth')} disagrees with "
                    f"{len(dids)} hops (depth should be hops-1)"
                )

        if kind == "revocation" and c.get("revoked_index") == c.get("clear_index"):
            errors.append(f"{name}: revoked_index and clear_index must differ")

    # SPEC.md leans on the multi-hop control; if it ever vanishes the rejection case
    # silently stops proving anything.
    if "token_multihop_reject_attenuated_away" in seen:
        if "token_multihop_parent_allows_before_attenuation" not in seen:
            errors.append(
                "the multi-hop rejection case is present without its control "
                "(token_multihop_parent_allows_before_attenuation) - the rejection "
                "would pass for the wrong reason"
            )

    jcs_count = check_jcs(errors)
    check_runner_agrees(errors)

    if errors:
        for e in errors:
            print(f"  FAIL  {e}", file=sys.stderr)
        print(f"\n{len(errors)} problem(s) in the vector files", file=sys.stderr)
        return 1

    kinds = sorted({c["kind"] for c in cases})
    print(f"vectors.json OK: format {suite['format']}, {len(cases)} cases, kinds {kinds}")
    print(f"jcs_vectors.json OK: format {SUPPORTED_JCS_FORMAT}, {jcs_count} cases")
    print("runner format constants agree with both files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
